default_platform(:ios)

platform :ios do
  desc "Deploy a new version to the App Store"
  lane :release do
    create_keychain(
      name: "ios-build.keychain",
      password: ENV["KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )

    match(
      type: "appstore",
      readonly: true,
      keychain_name: "ios-build.keychain",
      keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )

    build_ios_app(
      scheme: "Runner",
      export_options: "ExportOptions.plist",
      xcargs: "-allowProvisioningUpdates"
    )
  end
end

