default_platform(:ios)

platform :ios do
  desc "Deploy a new version to the App Store"
  lane :release do
    create_keychain(
      name: "ios-build.keychain",
      password: "fastlane123!",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )

    match(
      type: "appstore",
      readonly: true,
      keychain_name: "ios-build.keychain",
      keychain_password: "fastlane123!"
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "Runner.xcodeproj",
      targets: ["Runner"],
      code_sign_identity: "Apple Distribution",
      profile_name: "match AppStore com.sparkleo.demoRia",
      team_id: "KUU9HSKX4J"
    )

    build_ios_app(
      scheme: "Runner",
      export_method: "app-store",
      export_options: "ExportOptions.plist",
      codesigning_identity: "Apple Distribution",
      export_team_id: "KUU9HSKX4J",
      xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
        team_id: "KUU9HSKX4J",
        ipa: "./Runner.ipa",
        skip_waiting_for_build_processing: true
      )

  end
end
