default_platform(:ios)

platform :ios do
  desc "Deploy a new version to the App Store"
  lane :release do
    create_keychain(
      name: "ios-build.keychain",
      password: "fastlane123!",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )

    match(
      type: "appstore",
      readonly: true,
      keychain_name: "ios-build.keychain",
      keychain_password: "fastlane123!"
    )

    build_ios_app(
      scheme: "Runner",
      export_method: "app-store",
      export_options: "ExportOptions.plist", # You can remove this if overriding below
      codesigning_identity: "Apple Distribution",
      export_team_id: "KUU9HSKX4J", # Make sure this is the correct Apple Developer Team ID
      provisioning_profile_specifier: "match AppStore com.sparkleo.demoRia",
      xcargs: "-allowProvisioningUpdates"
    )
  end
end
