name: iOS App Store Deployment  

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'  # or latest stable Flutter  version supporting Dart 3.8

      - name: Install dependencies
        run: flutter pub get

      - name: Install Ruby and dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install fastlane
        run: |
          cd ios
          bundle install

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Debug secrets
        run: |
          echo "APPLE_ID is ${APPLE_ID:+set}"
          echo "FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD length: ${#FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD}"
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}



      - name: Build and deploy with Fastlane
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_PASSWORD: ria-demo-app
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
        run: |
          cd ios
          bundle exec fastlane release

